### ISSUE TITLE
Broken link to presentation slides

### ISSUE THREAD

**Issue by cybrjestr** [YosysHQ/riscv-formal#13]
Hi, 

on the [riscv-formal main page](https://github.com/YosysHQ/riscv-formal) on here, there is a link "See also [this presentation slides](http://bygone.clairexen.net/papers/2017/riscv-formal/) for an introduction to riscv-formal." Unfortunately, that link seems to be broken, the server times out whenever I try. Shame because I would be interested in the slides!

Thanks!

**Comment by KrystalDelusion** [comment]
I have managed to find the presentation slides being referenced.  With the exception of a bit more discussion on the 'whys' of end-to-end verification and using a framework such as riscv-formal, there doesn't seem to be much that isn't already in the included documentation.  

Being from 2017, they include a number of very out of date things in them, and unfortunately I do not have the source to be able to update them.  I am instead adding a brief section to the readme to provide an overview of getting a new core set up with riscv-formal.
