### ISSUE TITLE
Does riscv-formal Support Verification for Multi-Issue and Out-of-Order Processors?

### ISSUE THREAD

**Issue by SeddonShen** [YosysHQ/riscv-formal#27]
Hi,

I noticed that the RVFI interface description includes 'NRET', which denotes the maximum number of instructions that the core under test can retire in one cycle. I’m curious about the current support for out-of-order and multiple-issue processors in riscv-formal. Could you provide some insights?

Thank you!

**Comment by KrystalDelusion** [comment]
As far as I know it does support out-of-order processors:
> The `rvfi_order` field must be set to the instruction index. No indices must be used twice and there must be no gaps. Instructions may be retired in a reordered fashion, as long as causality is preserved (register and memory write operations must be retired before the read operations that depend on them).

There is support for multi core, though I'm not sure how fully implemented it is.  The current approach for atomic instructions won't work with multi core, but I'm not sure if there is anything else missing support.
