### ISSUE TITLE
The included SERV example fails most checks

### ISSUE THREAD

**Issue by jix** [YosysHQ/riscv-formal#9]
Only the causal, pc_bwd, pc_fwd and unique checks pass, the rest are failing.

I haven't looked into the reason for this yet. Finding out when things broke (i.e. trying different versions of riscv-formal, SERV and possibly even the oss-cad-suite) might be the easiest way to narrow down this issue.

**Comment by KrystalDelusion** [comment]
All checks except for liveness are passing in 0bbaa2016320452aae8c8c35b9d56e02c08d131d
